### ISSUE TITLE
!raid issue

### ISSUE THREAD

**Issue by mrlindstrom** [FoglyOgly/Meowth#1]
When using the !raid command, Meowth does not respond but creates the temporary room.  This is the output from the script:

Ignoring exception in command raid
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "meowth.py", line 980, in raid
    await Meowth.send_message(ctx.message.channel, content = "Meowth! {0} raid reported by {1}! Coordinate in {2}".format(raid.mention, ctx.message.author.mention, raid_channel.mention),embed=raid_embed)
AttributeError: 'NoneType' object has no attribute 'mention'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'mention'

**Comment by FoglyOgly** [comment]
Ah, yeah, I should put this in the readme. If he creates the channel but doesn't send the message, it's because no one has wanted that Pokemon yet. I should probably add code to create the role in the !raid command, but it could pretty easily be copied from the !want command if desired.

**Comment by FoglyOgly** [comment]
I fixed your issue in the raid command.

**Comment by mrlindstrom** [comment]
rock on!
