### ISSUE TITLE
Error when attempting to trade unown

### ISSUE THREAD

**Issue by BATShatner** [FoglyOgly/Meowth#227]
Issue :   execute '!trade unown' in the the trading channel and the following execption is thrown in the logs/request is cleared with in-channel

[28/07/2018 14:40] ERROR errors on_command_error 469: ConversionError
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 234, in _actual_conversion
    ret = await method(ctx, argument)
  File "/home/meowth/Meowth/meowth/exts/pokemon.py", line 383, in convert
    result = cls(ctx.bot, str(match), ctx.guild, shiny=shiny, alolan=alolan, form=form)
  File "/home/meowth/Meowth/meowth/exts/pokemon.py", line 102, in __init__
    if self.form not in form_dict.get(self.id, []):
TypeError: argument of type 'NoneType' is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 896, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 526, in invoke
    await self.prepare(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 491, in prepare
    await self._parse_arguments(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 418, in _parse_arguments
    kwargs[name] = await self.transform(ctx, param)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 308, in transform
    return (await self.do_conversion(ctx, converter, argument, param))
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 278, in do_conversion
    return await self._actual_conversion(ctx, converter, argument, param)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 242, in _actual_conversion
    raise ConversionError(converter, e) from e
discord.ext.commands.errors.ConversionError: (<class 'meowth.exts.pokemon.Pokemon'>, TypeError("argument of type 'NoneType' is not iterable",))

**Comment by scragly** [comment]
Found to be a case of list.extend being used inline expecting it to return the altered list, when extend doesn't return the result, it only alters the existing object.

Will make a commit shortly to resolve.
