### ISSUE TITLE
!raid and !raidex throw exception

### ISSUE THREAD

**Issue by StrGazer61** [FoglyOgly/Meowth#67]
clean clone and config throw exceptions
(FYI also had to install pillow and pytesseract requirements but no biggie)

Ignoring exception in command raid
Traceback (most recent call last):
  File "/home/x/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "meowth.py", line 1097, in raid
    await _raid(ctx.message)
  File "meowth.py", line 1100, in _raid
    if server_dict[message.server]['raidset'] == True:
KeyError: 'raidset'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/home/x/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/x/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'raidset'

**Comment by grogmanesquire** [comment]
It will throw that error if you DM !configure to meowth, you must use !configure in a channel it can see on your server.

**Comment by grogmanesquire** [comment]
did it throw this exception while running !configure? or did you maybe not complete !configure and tried to use the raid command?

**Comment by StrGazer61** [comment]
I did run it, and it completed, I checked the server_dict and the entries weren't there though, I ran again and it worked that time, weird, thanks for the info, closing
